public enum TipoEntidade{
    ROBO,
    ROBO_AEREO,
    ROBO_DESTRUIDOR,
    ROBO_GUINDASTE,
    ROBO_INATIVO,
    ROBO_LIMITADO,
    ROBO_TELETRANSPORTADOR,
    ROBO_TERRESTRE,
    OBSTACULO,
    DESCONHECIDO,
    VAZIO();
}